import { createFileRoute } from '@tanstack/react-router';
import { ContactBand, PageIntro } from '@/components/SiteLayout';
import { media } from '@/lib/site-data';
export const Route = createFileRoute('/about')({ head: () => ({ meta: [
  { title: 'About Kaajjal Rahul Jadhhav | Kaajjal’s Spiritual World' },
  { name: 'description', content: 'Meet Kaajjal Rahul Jadhhav and learn about her six-year journey in astrology, healing and personalized spiritual guidance in Pune.' },
  { property: 'og:title', content: 'About Kaajjal’s Spiritual World' }, { property: 'og:description', content: 'A welcoming practice for personal attention, self-awareness and spiritual guidance in Bibwewadi, Pune.' }, { property: 'og:type', content: 'website' }, { name: 'twitter:card', content: 'summary_large_image' },
] }), component: About });
function About() { return <><PageIntro label="ABOUT OUR WORLD" title="Guidance with heart." description="A welcoming space for self-awareness, clarity and an individual approach to every journey."/><section className="section-wrap"><div className="container-wide intro-grid"><div className="intro-visual"><video src={media.founderVideo} poster={media.founderPoster} controls playsInline preload="metadata"/><span className="intro-stamp">Meet Kaajjal.</span></div><div className="intro-text"><div className="eyebrow">THE FOUNDER</div><h2 className="section-title">Meet Kaajjal <em>Rahul Jadhhav.</em></h2><p>What began as a journey of exploring astrology and spirituality has grown into a platform dedicated to meaningful, personalized guidance.</p><p>Over the past six years, Kaajjal’s passion for astrology, healing and helping people explore their individual paths has shaped a diverse range of spiritual services and one-to-one consultations.</p><p>At the heart of her work is a belief that every person’s story deserves time, understanding and confidentiality.</p></div></div></section><section className="section-wrap services-band"><div className="container-wide"><div className="section-heading"><div><div className="eyebrow">WHAT GUIDES US</div><h2 className="section-title">Rooted in <em>intention.</em></h2></div></div><div className="value-grid"><div className="value-item"><span>01 /</span><h3>Our philosophy</h3><p>Spiritual practices can offer perspectives that help us reflect, understand ourselves and approach challenges with greater awareness.</p></div><div className="value-item"><span>02 /</span><h3>Our mission</h3><p>To create a trusted, welcoming space for personalized guidance across personal growth, relationships, career and business.</p></div><div className="value-item"><span>03 /</span><h3>Our vision</h3><p>A community where astrology, healing, knowledge and positive energy come together to inspire self-awareness and clarity.</p></div></div></div></section><section className="section-wrap"><div className="container-wide prose-section"><h2>Your journey is unique. Let’s understand it together.</h2><p>Whether you are looking for insights through your kundali, seeking tarot guidance, exploring reiki, looking for vastu solutions or considering business consultancy, Kaajjal’s Spiritual World is here to offer personalized guidance along the way.</p></div></section><ContactBand/></> }
