import { createFileRoute } from '@tanstack/react-router';
import { ArrowUpRight } from 'lucide-react';
import { PageIntro } from '@/components/SiteLayout';
export const Route = createFileRoute('/contact')({ head: () => ({ meta: [
  { title: 'Contact Us | Kaajjal’s Spiritual World, Bibwewadi Pune' },
  { name: 'description', content: 'Find Kaajjal’s Spiritual World in Bibwewadi, Pune. Get in touch to ask about spiritual consultations, services and courses.' },
  { property: 'og:title', content: 'Contact Kaajjal’s Spiritual World' }, { property: 'og:description', content: 'Connect with Kaajjal’s Spiritual World in Bibwewadi, Pune.' }, { property: 'og:type', content: 'website' }, { name: 'twitter:card', content: 'summary_large_image' },
] }), component: Contact });
function Contact() { return <><PageIntro label="LET’S CONNECT" title="Begin your journey." description="We’d love to hear what’s on your mind. Visit us in Bibwewadi, Pune, or reach out for details about consultations."/><section className="section-wrap"><div className="container-wide contact-layout"><div><div className="eyebrow">FIND OUR WORLD</div><h2>Some questions are better explored together.</h2><p>Whether you are seeking a reading, exploring healing or curious about courses, the first step is simply reaching out.</p><div className="contact-detail"><span>LOCATION</span><strong>Bibwewadi, Pune, India</strong><a className="map-link" href="https://www.google.com/maps/search/?api=1&query=Bibwewadi%2C+Pune" target="_blank" rel="noopener noreferrer">View area on map <ArrowUpRight size={15}/></a></div><div className="contact-detail"><span>FOUNDER</span><strong>Kaajjal Rahul Jadhhav</strong></div></div><div className="contact-note"><div className="eyebrow">CONTACT DETAILS</div><h2>Let’s talk when you’re ready.</h2><p>Direct booking details and a contact number have not been provided yet. For now, you can explore the services and find us in Bibwewadi, Pune. Please check back for an updated way to get in touch.</p></div></div></section></> }
